language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jbsulli/multi-docker-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jbsulli/multi-docker-client-test npm test

after_success:
  - docker build -t jbsulli/multi-docker-api ./api
  - docker build -t jbsulli/multi-docker-client ./client
  - docker build -t jbsulli/multi-docker-nginx ./nginx
  - docker build -t jbsulli/multi-docker-worker ./worker
  # log into docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker hub
  - docker push jbsulli/multi-docker-api
  - docker push jbsulli/multi-docker-client
  - docker push jbsulli/multi-docker-nginx
  - docker push jbsulli/multi-docker-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-west-2-113411857242
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
